### ISSUE TITLE
Atom 1.23 working remote-edit

### ISSUE THREAD

**Issue by janstieler** [urban-1/remote-edit2#2]
Hi,
the original Fork of remote-edit doesn't work in the actual atom version.
Here is a functional fork of[ remote-edit](https://github.com/newinnovations/remote-edit-ni). It would be cool if this would work with your enhancements of remote-edit.

Cheers

**Comment by urban-1** [comment]
Hi @janstieler 

We have been working towards merging with @newinnovations. You can find the result in `devel` branch at https://github.com/newinnovations/remote-edit-ni/tree/devel. The installation should be something along these lines:

```
git clone https://github.com/newinnovations/remote-edit-ni.git
cd remote-edit-ni
git checkout devel
apm install
apm link
```

Let us know (on newinnovations's fork) if this works for you :)

**Comment by janstieler** [comment]
Cool nice to hear.
Directly installed and on the first view it work like a charm!
Thumbs up.

One thing with I have often problems is, that a one click is open the file. I open this file mostly double because I'm trained that I have to do a double click to open.

**Comment by urban-1** [comment]
I do the same thing!

Let us merge and release a package on atom.io and next release I will try to do something about it. 

Thanks for the feedback btw. Feel free to close this issue.
